content = open('app.py', encoding='utf-8').read()
count = content.count('use_container_width=True')
fixed = content.replace('use_container_width=True', 'width="stretch"')
open('app.py', 'w', encoding='utf-8').write(fixed)
print(f'Fixed {count} occurrences of use_container_width=True')
